name: Deployment

on:
  push:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
        run: |-
          sleep 60
          echo "dev"
  prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: |-
          sleep 60
          echo "prod"
