on: issue_comment

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: verify approval
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash .github/bash.sh ${{ github.event.comment.body }} ${{ github.event.comment.user.login }}
      - name: deploy
        run: |
          echo ${{ env.DEPLOYMENT }}
          if ! ${{ env.DEPLOYMENT }} == 'APPROVED'; then
            echo Deployment not approved
          else
            echo Deploying
          fi
