on: issue_comment

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    runs-on: ubuntu-latest
    steps:
      - name: verify approval
        run: |
          bash .github/bash.sh
      - name: deploy
        run: |
          echo Deploying ...
